/* Tangled output generated by inweb: do not edit */
#include <stdio.h>
#define HELLO 1\
       CONT
#define GOODBYE 2
#define AND 3
#line 9 "inweb/Examples/hellow.inweb"
int  main(int argc, char *argv[]) ;
#line 8 "inweb/Examples/hellow.inweb"

int main(int argc, char *argv[]) {
	printf("Hello world!\n");
}

#line 25 "inweb/Examples/hellow.inweb"
int banana = 1;

